### ISSUE TITLE
Issues about UI components

### ISSUE THREAD

**Issue by liushuyu** [j-selby/liftinstall#13]
The current design uses `Vue.JS` and all the UI components are crammed into one single file which is very difficult for a new contributor to locate a specific component or view to work on or add a new feature.

Also the current design utilized a bunch of hacks to get it to work on older browsers like Internet Explorers which makes the things even worse.

I suggest using the current standard Vue.JS workflow that uses `Webpack`-oriented solution which takes older browsers into consideration while you can write the code in a newer ECMA standard without hacks in your code (the packer will use Babel to preprocess your source so that older browser will also work). Also, this will also split the components so that one component is one `.vue` file.

This will ease the future UI/UX designs and re-factors since everything is cut into smaller chunks so that potential new contributors can digest one chunk at a time.

Thanks

**Comment by j-selby** [comment]
Hi,

Yeah, the UI + web server does need some work in terms of cleaning up - I just haven't found the time to work on it unfortunately.

I did want to avoid pulling in Node dependencies for compiling the application, but I feel like that is a bit of wasted effort.

**Comment by liushuyu** [comment]
>I did want to avoid pulling in Node dependencies for compiling the application, but I feel like that is a bit of wasted effort.

Hmm... Well, I think I have guessed your incentive doing that a while ago. But the reality is, if keeping adding more features and more fixes, UI part will be growing uncontrollably (trust me, it will, as I currently see the needs to add several dialogs to hint users about certain actions like overriding a partially-removed or partially-installed situation).

So I guess you can just checking in the final packed version of the Javascript so that if someone does not want to do UI/UX job, they don't have to install Node.JS

I can understand installing `Node.JS` and using it is painful as it will dump `inf` GB of libraries onto your hard disk, but a project of this scale, I think it's better to consider it. 

Also, my latest PR (opened just now) would fix a bug reported several times on Yuzu forums. I have to admit it is not a bullet-proof 100%-covered fix. To mitigate the issue completely, I think `LiftInstall` needs to implement a functionality to be able to override the previous (failed/partial) install.

**Comment by j-selby** [comment]
Completed as of 5603981af142dd3f49cc8c7042899664bb490ff2
