### ISSUE TITLE
Yuzu crashes after first time I use it

### ISSUE THREAD

**Issue by lalejandrors** [j-selby/liftinstall#34]
Hi! I would like to report a problem. When I install Yuzu and play it the first time everything works fine. Then when I try to play the game after I close the game... it does not work any more. Any sugestions? Thanks! In some forums people say I have to delete cache or disabled the load of it in the options.

**Comment by j-selby** [comment]
Hi! I am not responsible for yuzu - please see their forums or Discord server for assistance. This doesn't appear to be an issue with liftinstall, so I will close this now.
