### ISSUE TITLE
I can't download yuzu

### ISSUE THREAD

**Issue by wmdhs12138** [j-selby/liftinstall#36]
![屏幕截图 2021-12-19 014214](https://user-images.githubusercontent.com/28940560/146651095-d10331b9-c9be-4a9d-ba5d-3251fb9dccf5.png)
[yuzu_installer.log](https://github.com/j-selby/liftinstall/files/7739695/yuzu_installer.log)

**Comment by j-selby** [comment]
LiftInstall currently needs a unblocked internet connection - from the log, it looks like that isn't the case for you (you need to be able to access GitHub).
